In [1]:
import pandas as pd

In [3]:
df=pd.read_csv('data.csv')
df

,Unnamed: 0,Brand,Model,Model_year,Transmission,Engine_size(cc),Drivetrain,Fuel_type,Lot_no,Kilometer,Price
0,0,Chevrolet,aveo,2009,Manual,1150,2,Petrol,6,200,975000
1,1,Chevrolet,captiva,2015,Automatic,2000,4,Diesel,8,100,3000000
2,2,Chevrolet,aveo,2009,Manual,1150,2,Petrol,6,42000,975000
3,3,Chevrolet,captiva,2010,Automatic,2000,4,Diesel,8,51000,3000000
4,4,Chevrolet,spark,2012,Manual,1000,2,Petrol,9,38000,1000000
...,...,...,...,...,...,...,...,...,...,...,...
1894,2209,Volkswagen,polo,2013,Manual,1600,2,Petrol,11,6300,2700000
1895,2210,Volkswagen,beetle,2010,Manual,1595,2,Petrol,8,19000,3950000
1896,2211,Volkswagen,passat,2010,Manual,1800,2,Petrol,8,11000,5800000
1897,2213,Volkswagen,tiguan,2010,Manual,2000,2,Petrol,8,25000,4900000
1898,2215,Volkswagen,vento,2012,Manual,1600,2,Diesel,11,14000,3555555

In [18]:
from sklearn.model_selection import train_test_split

,Unnamed: 0,Brand,Model,Model_year,Transmission,Engine_size(cc),Drivetrain,Fuel_type,Lot_no,Kilometer,Price
0,0,Chevrolet,aveo,2009,Manual,1150,2,Petrol,6,200,975000
1,1,Chevrolet,captiva,2015,Automatic,2000,4,Diesel,8,100,3000000
2,2,Chevrolet,aveo,2009,Manual,1150,2,Petrol,6,42000,975000
3,3,Chevrolet,captiva,2010,Automatic,2000,4,Diesel,8,51000,3000000
4,4,Chevrolet,spark,2012,Manual,1000,2,Petrol,9,38000,1000000
...,...,...,...,...,...,...,...,...,...,...,...
1894,2209,Volkswagen,polo,2013,Manual,1600,2,Petrol,11,6300,2700000
1895,2210,Volkswagen,beetle,2010,Manual,1595,2,Petrol,8,19000,3950000
1896,2211,Volkswagen,passat,2010,Manual,1800,2,Petrol,8,11000,5800000
1897,2213,Volkswagen,tiguan,2010,Manual,2000,2,Petrol,8,25000,4900000
1898,2215,Volkswagen,vento,2012,Manual,1600,2,Diesel,11,14000,3555555

In [20]:
X_train,X_test,y_train,y_test=train_test_split(df.drop('Price',axis=1),df['Price'],test_size=0.3,random_state=0)
X_train.shape,y_train.shape
X_train

,Unnamed: 0,Brand,Model,Model_year,Transmission,Engine_size(cc),Drivetrain,Fuel_type,Lot_no,Kilometer
940,940,Hyundai,accent,2009,Manual,1400,2,Petrol,7,43623
1108,1108,Mahindra,Kuv,2016,Manual,1200,2,Petrol,16,28000
432,432,Hyundai,i10,2010,Manual,1200,2,Petrol,9,31000
576,576,Hyundai,santro,2009,Manual,1100,2,Petrol,7,29000
658,658,Hyundai,asta,2010,Manual,1200,2,Petrol,8,36000
...,...,...,...,...,...,...,...,...,...,...
835,835,Hyundai,i10,2010,Manual,1200,2,Petrol,9,26000
1216,1221,Maruti Suzuki,Omni,2009,Manual,800,2,Petrol,7,52000
1653,1867,Tata,safari,2014,Manual,2200,4,Diesel,12,20000
559,559,Hyundai,i10,2010,Manual,1200,2,Petrol,7,30000
684,684,Hyundai,santro,2000,Manual,1000,2,Petrol,3,60000

In [12]:
from sklearn.preprocessing import StandardScaler

In [16]:
scaler = StandardScaler()

In [14]:
scaler.fit(X_train)

ValueError: could not convert string to float: 'Hyundai'